version: '3.3'
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "4999:8000"
    volumes:
        - /root/node/whabotapi/client/public:/app/app/qr
        - /mnt/disk2/fotosID:/app/app/img
        - /mnt/disk2/samba/files/tagsRefrendo:/app/app/tag
        - /mnt/disk2/bitacoraIO:/app/app/Enramada
    restart: always