version: '3.3'
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "4999:4999"
    volumes:
        - ./app/:/app/
        - /mnt/disk2/fotosID:/app/img
        - /mnt/disk2/samba/files/tagsRefrendo:/app/tag
        - /mnt/disk2/bitacoraIO:/app/Bitacora
    restart: always
    environment:
      - TZ=America/Mexico_City
