version: '3.3'
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "4999:8000"
    volumes:
        - ./app/:/app/
        - /root/node/whabotapi/client/public:app/qr
        - /mnt/disk2/fotosID:app/img
        - /mnt/disk2/samba/files/tagsRefrendo:app/tag
        - /mnt/disk2/bitacoraIO:app/Enramada
        - /mnt/disk2/bitacoraIO:app/Bitacora
    restart: always
    environment:
      - TZ=America/Mexico_City