version: '3.3'
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "4999:8000"
    volumes:
        - ./app/:/app/
        - /mnt/4tb/fotosID:/app/img
        - /mnt/4tb/samba/files/tagsRefrendo:/app/tag
        - /mnt/4tb/bitacoraIO:/app/Bitacora
    restart: always
    environment:
      - TZ=America/Mexico_City
