version: '3.3'
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "4999:8000"
    volumes:
        - /root/node/whabotapi/client/public:/app/app/qr
        - /mnt/disk0/images:/app/app/pai
        - /mnt/disk2/logTags:/app/app/Castrosa